[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[context.master.environment]
  GOOGLE_ANALYTICS_ID = 'UA-XXX-X'
[context.production.environment]
  GOOGLE_ANALYTICS_ID = 'UA-XXX-X'